project_id = "gryqnaypifpzmmmfwxhi"

[functions.auth-check-user]
verify_jwt = false

[functions.auth-onboard]
verify_jwt = false

[functions.auth-send-otp]
verify_jwt = false

[functions.auth-verify-otp]
verify_jwt = false